-- PRODUCT 테이블과 OFFLINE_SALE 테이블에서 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
-- 결과는 매출액을 기준으로 내림차순 정렬해주시고 매출액이 같다면 상품코드를 기준으로 오름차순 정렬

-- Solution 1
SELECT PRODUCT.PRODUCT_CODE AS PRODUCT_CODE,
        PRODUCT.PRICE * OFF_SALE.SALES_AMOUNT_PRODUCT_ID AS SALES
FROM PRODUCT
RIGHT JOIN (SELECT PRODUCT_ID,
                SUM(OFFLINE_SALE.SALES_AMOUNT) AS SALES_AMOUNT_PRODUCT_ID
            FROM OFFLINE_SALE
            GROUP BY PRODUCT_ID) OFF_SALE
ON PRODUCT.PRODUCT_ID = OFF_SALE.PRODUCT_ID
ORDER BY SALES DESC,
            PRODUCT_CODE ASC

-- Solution 2
# -- OVER, PARTITION BY
# SELECT PRODUCT.PRODUCT_CODE AS PRODUCT_CODE,
#         PRODUCT.PRICE * COUNT_OFFLINE_SALES.SALES_COUNT AS SALES
# FROM PRODUCT
# RIGHT JOIN (SELECT DISTINCT PRODUCT_ID,
#         SUM(SALES_AMOUNT) OVER (PARTITION BY PRODUCT_ID) AS SALES_COUNT
# FROM OFFLINE_SALE) COUNT_OFFLINE_SALES
# ON PRODUCT.PRODUCT_ID = COUNT_OFFLINE_SALES.PRODUCT_ID
# ORDER BY SALES DESC,
#             PRODUCT_CODE ASC