-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 
-- ID와 이름을 
-- ID 순으로 조회

SELECT ANIMAL_OUTS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_OUTS.NAME AS NAME
FROM ANIMAL_INS
RIGHT JOIN ANIMAL_OUTS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
-- check whether ANIMAL_INS.ANIMAL_ID is NULL
WHERE ISNULL(ANIMAL_INS.ANIMAL_ID)
ORDER BY ANIMAL_ID;