SELECT ECONOMY.BOOK_ID, 
        AUTHOR.AUTHOR_NAME, 
        DATE_FORMAT(ECONOMY.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM (SELECT *
      FROM BOOK
      WHERE CATEGORY = '경제'
     ) ECONOMY
LEFT JOIN AUTHOR
ON ECONOMY.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC;
