SELECT *
FROM(
    SELECT
        CAR.CAR_ID,
        CAR.CAR_TYPE,
        ROUND((100 - PLAN.DISCOUNT_RATE) / 100 * CAR.DAILY_FEE * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS CAR, CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
    WHERE
        CAR.CAR_TYPE = PLAN.CAR_TYPE 
        AND CAR.CAR_TYPE IN ('세단', 'SUV')
        AND CAR.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
            WHERE 
                END_DATE BETWEEN DATE(20221101) AND DATE_SUB(20221201, INTERVAL 1 SECOND)
                OR 
                (END_DATE > DATE(20221201)
                    AND START_DATE <= DATE_SUB(20221201, INTERVAL 1 SECOND)) 
                -- Contains the case when START_DATE within November
        )
        AND PLAN.DURATION_TYPE = "30일 이상"
) TOTAL
WHERE (TOTAL.FEE >= 500000) AND (TOTAL.FEE < 2000000)
ORDER BY TOTAL.FEE DESC, CAR_TYPE ASC, CAR_ID DESC